"""empty message

Revision ID: 1f15e96b1320
Revises: 
Create Date: 2023-03-02 17:53:50.076018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f15e96b1320'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('lastLoginTime', sa.String(length=20), nullable=False),
    sa.Column('serverId', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('clanId', sa.String(length=20), nullable=False),
    sa.Column('clanRole', sa.String(length=20), nullable=False),
    sa.Column('avatarId', sa.String(length=20), nullable=False),
    sa.Column('isChatModerator', sa.Boolean(), nullable=False),
    sa.Column('frameId', sa.Integer(), nullable=False),
    sa.Column('leagueId', sa.Integer(), nullable=False),
    sa.Column('allowPm', sa.String(length=20), nullable=False),
    sa.Column('accountId', sa.String(length=20), nullable=False),
    sa.Column('timeZone', sa.Integer(), nullable=False),
    sa.Column('starMoney', sa.String(length=20), nullable=False),
    sa.Column('vipPoints', sa.String(length=20), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('flags', sa.String(length=20), nullable=False),
    sa.Column('nextDayTs', sa.Integer(), nullable=False),
    sa.Column('nextServerDayTs', sa.Integer(), nullable=False),
    sa.Column('experience', sa.String(length=20), nullable=False),
    sa.Column('maxLevel', sa.String(length=20), nullable=False),
    sa.Column('registrationTime', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
